import SwiftUI

/// SF Symbol vocabulary. Names mirror the Material Symbols used in docs/design/v2.
enum AppIcon: String, Sendable {
    case back = "chevron.left"
    case bolt = "bolt.fill"
    case calendar = "calendar"
    case camera = "camera"
    case capture = "plus.circle.fill"
    case check = "checkmark"
    case checkCircle = "checkmark.circle"
    case chevronDown = "chevron.down"
    case chevronRight = "chevron.right"
    case clock = "clock"
    case close = "xmark"
    case cloudUpload = "icloud.and.arrow.up"
    case cpu = "cpu"
    case download = "square.and.arrow.down"
    case ellipsis = "ellipsis"
    case eyeSlash = "eye.slash"
    case flag = "flag"
    case heart = "heart"
    case history = "clock.arrow.circlepath"
    case home = "house"
    case journal = "square.and.pencil"
    case key = "key"
    case listPlus = "text.badge.plus"
    case microphone = "mic"
    case pause = "pause.fill"
    case pencil = "pencil"
    case personSlash = "person.slash"
    case phone = "iphone"
    case play = "play.fill"
    case plus = "plus"
    case prepare = "calendar.badge.clock"
    case questionmark = "questionmark.circle"
    case quote = "quote.opening"
    case search = "magnifyingglass"
    case settings = "gearshape"
    case share = "square.and.arrow.up"
    case shield = "lock.shield"
    case sliders = "slider.horizontal.3"
    case sparkles = "sparkles"
    case stop = "stop.fill"
    case toggle = "switch.2"
    case trash = "trash"
    case volume = "speaker.wave.2"
    case waveform = "waveform"

    var image: Image { Image(systemName: rawValue) }
}
